[package]
name = "java2rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[toolchain]
channel = "nightly"

[dependencies]
clap = { version = "3.0.7", features = ["derive"] }
tree-sitter = "0.17"
tree-sitter-java = "0.16"
lazy_static = "1.4.0"
